# !bin/zsh
# This will generate the rules for the subdomains
# It uses the runs folder and domain file
source .venv36/bin/activate

# export RULE_SIZE=2
export DOMAIN_FILE_SATELITES="useful-actions-dataset-main/satellite/runs/optimal/p01-2-2-2-5-1/domain.pddl"
# export DOMAIN_FILE_DEPOTS="useful-actions-dataset/depots/runs/optimal/p01-1-1-2-2-2-4/domain.pddl"

# export RUNS_DIR_DEPOTS="useful-actions-dataset/depots/runs/optimal"
export RUNS_DIR_SATELITE="useful-actions-dataset-main/satellite/runs/optimal"

export RESULTS_FILE="results/sat_with_runs_size3.csv"

python ./src/subdominization-training/gen-subdom-rules.py --store_rules $RESULTS_FILE --rule_size 3 --runs $RUNS_DIR_SATELITE $DOMAIN_FILE_SATELITES
# python ./src/subdominization-training/gen-subdom-rules.py --rule_size 2 --store_rules $RESULTS_FILE $DOMAIN_FILE_DEPOTS